"""
scripts/gen_version.py
----------------------
Generates src/version.py before a PyInstaller build.

Called by build_exe.ps1 / build_exe.bat as:
    python scripts/gen_version.py

Reads:
  - Latest git tag (MAJOR.MINOR.PATCH, no hash) via:
        git describe --tags --abbrev=0
    Falls back to the existing __version__ in src/version.py if git is
    unavailable or no tags exist.

  - Current calendar year from the system clock.

Writes src/version.py with __version__, __build_year__, and CREDIT.
"""

import subprocess
import datetime
import os
import sys
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(ROOT, "src", "version.py")

# ── Fallback: read existing version from src/version.py ──────────────────────
def _read_existing_version() -> str:
    try:
        with open(OUT, "r") as f:
            for line in f:
                m = re.match(r'__version__\s*=\s*["\']([^"\']+)["\']', line)
                if m:
                    return m.group(1)
    except FileNotFoundError:
        pass
    return "1.0.2"

# ── Git tag ───────────────────────────────────────────────────────────────────
def _get_git_version() -> str:
    try:
        raw = subprocess.check_output(
            ["git", "describe", "--tags", "--abbrev=0"],
            cwd=ROOT,
            stderr=subprocess.DEVNULL,
            timeout=5,
        ).decode().strip()
        # Strip leading 'v' if present
        raw = raw.lstrip("v")
        # Validate it looks like a semver string
        if re.match(r"^\d+\.\d+(\.\d+)?", raw):
            return raw
    except Exception:
        pass
    return _read_existing_version()

# ── Main ──────────────────────────────────────────────────────────────────────
version    = _get_git_version()
build_year = datetime.datetime.now().year
credit     = f"Built by Prashant Srinivasan {build_year}  |  v{version}"

content = f'''\
# AUTO-GENERATED - do not edit manually
# Generated by scripts/gen_version.py at build time.
# Committed value used as fallback when running from source without a build.

__version__    = "{version}"
__build_year__ = {build_year}
CREDIT         = "{credit}"
'''

with open(OUT, "w", encoding="utf-8") as f:
    f.write(content)

print(f"[gen_version] v{version}  year={build_year}")
print(f"[gen_version] Written -> {OUT}")
