# AUTO-GENERATED - do not edit manually
# Generated by scripts/gen_version.py at build time.
# Committed value used as fallback when running from source without a build.

__version__    = "1.1.0"
__build_year__ = 2026
CREDIT         = "Built by Prashant Srinivasan 2026  |  v1.1.0"
